Repository Mercandj/presentation, pull requests merged in 2019-02, with the labels that each got.

#22 [DynamicDelivery] Add slides about BundleTool
  mwm-5-dynamic-delivery/presentation/PITCHME.md
Labels: auto-review

#23 [DynamicDelivery] Fix bundle tool slides
  mwm-5-dynamic-delivery/presentation/PITCHME.md
Labels: auto-review

#24 [DynamicDelivery] Add android app bundle explanation
  mwm-5-dynamic-delivery/presentation/PITCHME.md
  mwm-5-dynamic-delivery/presentation/android-app-bundle-details.png
  mwm-5-dynamic-delivery/presentation/android-app-bundle.png
Labels: auto-review

#30 [DynamicDelivery] Add explanation about consent dialog for big module…
  mwm-5-dynamic-delivery/presentation/PITCHME.md
Labels: reviewed

#29 [DynamicDelivery] Add install request listener explanation
  mwm-5-dynamic-delivery/presentation/PITCHME.md
Labels: reviewed

#27 [DynamicDelivery] Add explanation on dist:title
  mwm-5-dynamic-delivery/presentation/PITCHME.md
Labels: reviewed

#26 [DynamicDelivery] Fix base module build.gradle
  mwm-5-dynamic-delivery/presentation/PITCHME.md
Labels: reviewed

#33 [DynamicDelivery] Add explanation on dynamic module manifest
  mwm-5-dynamic-delivery/presentation/PITCHME.md
Labels: reviewed

#32 [DynamicDelivery] Fix install listener and user consent dialog explanations
  mwm-5-dynamic-delivery/presentation/PITCHME.md
Labels: reviewed

#31 [DynamicDelivery] Add uninstall module explanation
  mwm-5-dynamic-delivery/presentation/PITCHME.md
Labels: reviewed

#36 [DynamicDelivery] RunDebug section, example section, creation section
  mwm-5-dynamic-delivery/presentation/PITCHME.md
  mwm-5-dynamic-delivery/presentation/run-debug.png
  mwm-5-dynamic-delivery/presentation/tuto-1.png
  mwm-5-dynamic-delivery/presentation/tuto-2.png
Labels: reviewed

#34 [DynamicDelivery] Complete install section with listener and deferred
  mwm-5-dynamic-delivery/presentation/PITCHME.md
  mwm-5-dynamic-delivery/presentation/run-debug.png
  mwm-5-dynamic-delivery/presentation/tuto-1.png
  mwm-5-dynamic-delivery/presentation/tuto-2.png
Labels: reviewed

#37 [DynamicDelivery] Add explanation to disable shrinkResources
  mwm-5-dynamic-delivery/presentation/PITCHME.md
Labels: reviewed

#38 [DynamicDelivery] Add explanation about resources used in manifest of a dynamic module
  mwm-5-dynamic-delivery/presentation/PITCHME.md
Labels: reviewed

#39 [DynamicDelivery] Add explanation to load native lib from dynamic module
  mwm-5-dynamic-delivery/presentation/PITCHME.md
Labels: reviewed

#41 [DynamicDelivery] Reorganize slides
  mwm-5-dynamic-delivery/presentation/PITCHME.md
Labels: auto-review

#43 [DynamicDelivery] Add contex to dist module in manifest examples
  mwm-5-dynamic-delivery/presentation/PITCHME.md
Labels: reviewed

#44 [DynamicDelivery] Add explanation to update context to access resources
  mwm-5-dynamic-delivery/presentation/PITCHME.md
Labels: to-review

#42 [DynamicDelivery] Install download progress
  mwm-5-dynamic-delivery/presentation/PITCHME.md
Labels: reviewed

#45 [DynamicDelivery] Improve fullsize gradle
  mwm-5-dynamic-delivery/presentation/PITCHME.css
  mwm-5-dynamic-delivery/presentation/PITCHME.md
Labels: reviewed

#46 [DynamicDelivery] Improve slides title and commentaries
  mwm-5-dynamic-delivery/presentation/PITCHME.md
Labels: reviewed

#47 [DynamicDelivery] Advance section
  mwm-5-dynamic-delivery/presentation/PITCHME.md
Labels: see-comments
